title: Visualization Techniques of Time-Oriented Data for the Comparison of Single Patients With Multiple Patients or Cohorts - Scoping Review
logo: /assets/img/logo.png
description: Companion website for publication Scheer et al. (2022) Journal of Medical Internet Research
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
